spring:
  profile.active: dev, test
  datasource:
    url: jdbc:mysql://localhost:3307/foro
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: always
api:
  security:
    secret: ${JWT_SECRET:123456}


